
# Synopsis:
#   ansible-playbook -f 50 -i "localhost," $OPS_HOME/checkports.yml -e "PORTFILE=$PWD/openapi-dev-ports-internals.json REPORTFILE=$PWD/ports-internals.json"
#
# Dependencies:
#  checkport-tasks.yml
#

---
- hosts: all

  tasks:
  - include_vars: file={{ PORTFILE }} name=topology

  - set_fact:
      report: []

  - name: Task
    include: checkport-tasks.yml C={{item.c}} S={{item.s}} P={{item.p}}
    register: command_result
    ignore_errors: true
    with_items: "{{ topology.ports }}"

  - name: Print report
    local_action: copy content="{{ report | to_nice_json }}" dest={{ REPORTFILE | default( '/tmp/report.json' ) }}
