#
# Usage:
#
# ansible-playbook -l n02 $OPS_HOME/fetch-logs.yml -e "DESTDIR=$PWD"
#
# n02 -- zookeeper node
#

---

- name: Fetch var/log for all notes
  hosts: all
  remote_user: apigee
  become: yes

  vars:
     # DESTDIR:
     TIMESTAMP: "{{lookup('pipe','date -u +\"%Y-%m-%dT%H:%M:%SZ\"')}}"


  tasks:
  - set_fact:
     ZKTREEFILE: "{{ inventory_hostname }}-zktree-{{ TIMESTAMP }}.txt"

  - shell: "/opt/apigee/apigee-zookeeper/contrib/zk-tree.sh > /tmp/{{ ZKTREEFILE }}"

#  - archive:
#      path: "/tmp/{{ ZKTREEFILE }}"
#      dest: "/tmp/{{ ZKTREEFILE }}.tgz"

  - fetch:
      src: "/tmp/{{ ZKTREEFILE }}"
      dest: "{{ DESTDIR }}/{{ ZKTREEFILE }}"
      flat: yes



