---

- hosts: all
  gather_facts: no
  
  vars: 
    service_account_email: gce-account@dark-safeguard-152518.iam.gserviceaccount.com
    credentials_file: /Users/yuriylesyuk/.ssh/EDGE-Squared-4e8de82ed05f.json
    project_id: 

  tasks:
    - local_action:
        module: gce_net
        name: default
        fwname: test-http-8000
        allowed: tcp:9000
        src_range: "0.0.0.0/0"
        src_tags: ["yl-n1-1701-aio"]
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
