---

- hosts: all
  gather_facts: no
  
  vars: 
    # VMCFG
    # GOOGLE_PROJECT_ID
    # GOOGLE_CLIENT_EMAIL
    # GOOGLE_JSON_KEY_LOCATION
    # RULE:    # firewall rule name
    # ALLOW:   # 'tcp:80' or 'tcp:80,443' or 'tcp:80-800;udp:1-25'
    TAGS: "{{ VMCFG }}"

  tasks:
    - local_action:
        module: gce_net
        name: default
        fwname: "{{ RULE | default( 'allow-on-{{ VMCFG }}' ) }}"
        allowed: "{{ ALLOW | default( 'tcp:8080,9000,9001-9010' ) }}"
        src_range: "0.0.0.0/0"
        target_tags: ["{{ TAGS }}"]
        service_account_email: "{{ GOOGLE_CLIENT_EMAIL }}"
        credentials_file: "{{ GOOGLE_JSON_KEY_LOCATION }}"
        project_id: "{{ GOOGLE_PROJECT_ID }}"
