---

- include: prereqs.yml

- include: server.yml

- include: networking.yml
- include: selinux.yml
- include: fw-{{ PROVIDER }}.yml

- name: Edge AIO Install and Config
  hosts: all
  become: yes
  become_method: sudo
  vars:
    # IP1: 10.132.0.3
    # PROVIDER: vb|gce

