#
# Synopsis:
# ansible-playbook ~/dbc/edge-ops/ansible/registerinstance.yml -e "VMCFG=$PWD/edge5n5-exco-com.cfg VMDIR=$PWD PROVIDER=gce" -u root --ask-sudo-pass
#

---
- hosts: localhost
  gather_facts: no
    
  vars:
    name: "{{lookup('ini', 'name section=vmconfig file={{VMCFG}}')}}"
    hostname: "{{lookup('ini', 'hostname section=vmconfig file={{VMCFG}}')}}"
    vm_box: "{{lookup('ini', 'vm.box section={{PROVIDER}}-provider file={{VMCFG}}')}}"
    zone: "{{lookup('ini', 'zone section={{PROVIDER}}-provider file={{VMCFG}}')}}"

    LOCAL_USER: "{{lookup('ini', 'LOCAL_USER section=vmconfig file={{VMCFG}}')}}"
    LOCAL_SSH_KEY: "{{lookup('ini', 'LOCAL_SSH_KEY section=vmconfig file={{VMCFG}}')}}"
    
  tasks:
    - local_action:
        module: shell
        args: "vagrant ssh-config | grep HostName | awk '{print $2}'"
        chdir: "{{ VMDIR }}/{{ name }}"
      register: instance_ip

    - set_fact:
        HOSTIP: "{{instance_ip.stdout }}"

    - fail: msg="Empty IP address. Is the {{ name }} instance running?"
      when: HOSTIP == ""

   #- name: #Add vagrant instance to local /etc/hosts
    - debug: msg="{{hostname}}"

    - local_action: 
        module: lineinfile
        state: present
        dest: "/etc/hosts"
        regexp: '^.*{{ hostname }}'
        line: "{{ HOSTIP }} {{ hostname }}"
      become: yes
      become_method: sudo

    - name: Add vagrant instance to local ~/.ssh/config
      local_action:
        module: blockinfile
        state: present
        dest: ~/.ssh/config
        marker: "# {mark} Ansible Managed Block [{{ hostname }}]"
        content: |
          Host {{ hostname }}
              IdentityFile {{ LOCAL_SSH_KEY }}
    
      
    - name: Add vagrant instance to local ~/ansible/hosts
      local_action:
        module: lineinfile
        state: present
        dest: ~/ansible/hosts
        insertbefore: BOF
        regexp: '^{{ hostname }}'
        line: "{{ hostname }} ansible_host={{ HOSTIP }} ansible_user={{ LOCAL_USER }} ansible_ssh_private_key_file={{ LOCAL_SSH_KEY }}"
        
