
#Usage example:
#  ansible-playbook ~/dbc/edge-ops/ansible/vagrantfile.yml -vvv  -e "VMCFG=$PWD/gce-aio-1701-6.cfg VMDIR=$PWD"
# 

---

- name: Vagrantfile generation
  hosts: localhost
  vars:
    # VMCFG:
    # PROVIDER: gce|vb
    PROVIDER: "{{lookup('ini', 'PROVIDER section=vmconfig file={{VMCFG}}')}}"
    name: "{{lookup('ini', 'name section=vmconfig file={{VMCFG}}')}}"
    vm_box: "{{lookup('ini', 'vm.box section={{PROVIDER}}-provider file={{VMCFG}}')}}"
    zone: "{{lookup('ini', 'zone section={{PROVIDER}}-provider file={{VMCFG}}')}}"
    machine_type: "{{lookup('ini', 'machine_type section={{PROVIDER}}-provider file={{VMCFG}}')}}"
    disk_type: "{{lookup('ini', 'disk_type section={{PROVIDER}}-provider file={{VMCFG}}')}}"

    GOOGLE_PROJECT_ID: "{{lookup('ini', 'GOOGLE_PROJECT_ID section={{PROVIDER}}-provider file={{VMCFG}}')}}"
    GOOGLE_CLIENT_EMAIL: "{{lookup('ini', 'GOOGLE_CLIENT_EMAIL section={{PROVIDER}}-provider file={{VMCFG}}')}}"
    GOOGLE_JSON_KEY_LOCATION: "{{lookup('ini', 'GOOGLE_JSON_KEY_LOCATION section={{PROVIDER}}-provider file={{VMCFG}}')}}"

    LOCAL_USER: "{{lookup('ini', 'LOCAL_USER section=vmconfig file={{VMCFG}}')}}"
    LOCAL_SSH_KEY: "{{lookup('ini', 'LOCAL_SSH_KEY section=vmconfig file={{VMCFG}}')}}"

    VMDESTDIR: "{{ VMDIR }}/{{ name }}"


  tasks:
  
  - debug: 
      msg: "{{ vm_box }}"
    
      
  - debug: 
      msg: "{{lookup('ini', 'zone section={{ PROVIDER }}-provider file=/Users/yuriylesyuk/vagrants/gce-aio-1701-6.cfg')}}"
      
  - set_fact:
      ip_ini: "{{lookup('ini', 'vm.box section={{PROVIDER}}-provider file={{VMCFG}}')}}"
  

  - debug: 
      msg: ">>> {{ hostvars[inventory_hostname]['ip_ini'] }}"
  
  - file: path={{VMDESTDIR}} state=directory
  - template: src=../vagrant/Vagrantfile.{{ PROVIDER }}.j2 dest="{{VMDESTDIR}}/Vagrantfile"
    delegate_to: localhost
